---
name: Build and push to GCP
on: 
  push:
    branches:
      - main
    paths:
      - docs/**
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docs
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      REPOSITORY: ${{ vars.REPOSITORY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        access_token_lifetime: 300s

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: europe-west3-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest ./docs

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ github.run_number }}
      run: |-
        docker tag $IMAGE_NAME:latest europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:2.20.1$GIT_TAG
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:2.20.1$GIT_TAG